### ISSUE TITLE
Possible issue with file helm/ckan/templates/ckan-deployment.yaml

### ISSUE THREAD

**Issue by shepardo** [jhinds/helm-ckan#1]
When installing the ckan files, like with 
`helm install ./helm/ckan -n ckan --debug`
there is an error due to an unexpected "{ end }":

` Error: parse error in "ckan/templates/ckan-deployment.yaml": template: ckan/templates/ckan-deployment.yaml:89: unexpected {{end}}
`
Now, I could remove the offending line, but it seems that some control structure is missing (the previous line "{{ toYaml . | indent 8 }}" seems to be the body of an inexistent loop, I removed it too, but looks like something is missing since I got other errors).

As better context, an screenshot of the file contents with the offending line highlighted is included.

Thanks

![Screen Shot 2019-05-03 at 4 04 00 PM](https://user-images.githubusercontent.com/1685248/57142578-27790580-6dbd-11e9-851b-772ec560e3e3.png)

**Comment by shepardo** [comment]
Actually, I got it working for by removing the lines 88 & 89, then there was the complaint of unknown volume "spec.template.spec.containers[0].volumeMounts[1].name: Not found: "ckan-apache-config", which I fixed by adding these lines to the volumes (line 88)


## adding these on new line 98
        - name: ckan-apache-config
          configMap:
            name: {{ .Values.volumes.ckanConfigMap }}

**Comment by shepardo** [comment]
I guess the root cause of all the problems is that a configmap was missing in the repo, I added one, have been tweaking it.

**Comment by pbajrami** [comment]
Hello @shepardo 
Did you make it work? Can you share the configmap that you added? Thanks!

**Comment by jhinds** [comment]
Sorry folks I didn't know anyone was using this and didn't have notifications so the first time I saw these messages was yesterday 🙈 . I merged in some changes that should fix this issue with a bunch of other updates to bring the chart up to date.
